#!/usr/bin/env python3
"""Convert the MAME 'tempest' ROM set into a C header for SPINDLE.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)

Tempest has no graphics ROMs: the picture is a list of vectors. What there is:
20 KB of program, a 4 KB vector ROM the vector generator walks, and the 256-byte
PROM that drives the generator's state machine.

The math box PROMs in the set are not needed. The real board's math box is a
bit-slice ALU running microcode out of them; this emulates the arithmetic it
performs rather than the microcode that performs it, exactly as MAME does.
"""
import sys, zlib
from pathlib import Path

# (name, load address, size); the last one is also mirrored at 0xF000 for the vectors
PROGRAM = [('136002-133.d1',  0x9000, 0x1000),
           ('136002-134.f1',  0xa000, 0x1000),
           ('136002-235.j1',  0xb000, 0x1000),
           ('136002-136.lm1', 0xc000, 0x1000),
           ('136002-237.p1',  0xd000, 0x1000)]
VECTORROM = ('136002-138.np3', 0x1000)
AVGPROM   = ('136002-125.d7',  0x0100)

CRCS = {'136002-133.d1': 0x1d0cc503, '136002-134.f1': 0xc88e3524,
        '136002-235.j1': 0xa4b2ce3f, '136002-136.lm1': 0x65a9a9f9,
        '136002-237.p1': 0xde4e9e34, '136002-138.np3': 0x9995256d,
        '136002-125.d7': 0x5903af03}

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'error: {name} not found in {romdir}\n'
                 f'       you need MAME\'s "tempest" set (revision 3); unzip it there')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'error: {name} is {len(data)} bytes, expected {size}')
    crc = zlib.crc32(data) & 0xffffffff
    want = CRCS.get(name)
    if want is not None and crc != want:
        sys.exit(f'error: {name} has crc32 {crc:08x}, expected {want:08x}\n'
                 f'       this is a different revision; SPINDLE is built for "tempest" rev 3')
    print(f'  {name}: {len(data)} bytes, crc32 {crc:08x}')
    return data

def c_array(name, data, dims):
    out = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        out.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    out.append('};')
    return '\n'.join(out)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'tempest')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')

    rom = bytearray(0x10000)
    for name, addr, size in PROGRAM:
        rom[addr:addr+size] = load(romdir, name, size)
    # the last program ROM is wired in twice so the reset and interrupt vectors are readable
    rom[0xf000:0x10000] = rom[0xd000:0xe000]

    vec = load(romdir, *VECTORROM)
    prom = load(romdir, *AVGPROM)

    out = ['/* tempest_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef TEMPEST_ROMS_H', '#define TEMPEST_ROMS_H', '#include <stdint.h>', '',
           c_array('tp_rom', bytes(rom), '[0x10000]'), '',
           c_array('tp_vectorrom', vec, '[0x1000]'), '',
           c_array('tp_avgprom', prom, '[0x100]'), '',
           '#endif']
    (outdir / 'tempest_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "tempest_roms.h"}')

if __name__ == '__main__':
    main()
